services:
    db:
        image: mysql:8.0
        container_name: mysql_desafio_container
        restart: always
        env_file:
            - ./config/.env
        environment:
            - TZ=America/Sao_Paulo
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - proj_bank_network

    backend:
        depends_on:
            - db
        env_file:
            - ./config/.env
        restart: always
        build: .
        container_name: obj_proj_container
        ports:
            - "5284:5284"
        networks:
            - proj_bank_network

volumes:
    db_data: {}
networks:
    proj_bank_network:
        name: proj_bank_network
        driver: bridge
