// <auto-generated />
using System;
using Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250527192533_CreateTable_Movimentacoes")]
    partial class CreateTable_Movimentacoes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entidades.Conta", b =>
                {
                    b.Property<int>("NumeroConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Numero");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NumeroConta"));

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Saldo");

                    b.HasKey("NumeroConta");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Movimentacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Data");

                    b.Property<int>("NumeroConta")
                        .HasColumnType("int")
                        .HasColumnName("Numero_Conta");

                    b.Property<decimal>("SaldoAntes")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Saldo_Antes");

                    b.Property<decimal>("SaldoDepois")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Saldo_Depois");

                    b.Property<string>("TipoTransacao")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("Tipo_Transacao")
                        .HasComment("Tipos Transação (P, D, C)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroConta");

                    b.ToTable("Movimentacoes", (string)null);
                });

            modelBuilder.Entity("Domain.Entidades.Movimentacao", b =>
                {
                    b.HasOne("Domain.Entidades.Conta", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("NumeroConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Domain.Entidades.Conta", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
